// SPDX-License-Identifier: MIT
pragma solidity 0.8.4;
import "hardhat/console.sol";

contract HfPriceOracleMock {
  mapping(address => uint) public prices;

  function setUnderlyingPrice(address cToken_, uint price_) external {
    console.log("HfPriceOracleMock.setUnderlyingPrice");
    prices[cToken_] = price_;
  }

  function ethUsdChainlinkAggregatorAddress() external pure returns (address) {
    return 0xF9680D99D6C9589e2a93a78A04A279e509205945;
  }

  /// @notice Indicator that this is a PriceOracle contract (for inspection)
  function isPriceOracle() external pure returns (bool) {
    return true;
  }

  function owner() external pure returns (address) {
    return 0xD0A27F0eBA2B407f2cCA8327b4Adb50BBAddFF24;
  }

  function getUnderlyingPrice(address cToken_) external view returns (uint256) {
    console.log("HfPriceOracleMock.getUnderlyingPrice");
    return prices[cToken_];
  }

  function renounceOwnership() external {
    console.log("HfPriceOracleMock.renounceOwnership");
  }

  function setEthUsdChainlinkAggregatorAddress(address addr) external pure {
    addr;
  }

  function setTokenConfigs(
    address[] memory cTokenAddress,
    address[] memory chainlinkAggregatorAddress,
    uint256[] memory chainlinkPriceBase,
    uint256[] memory underlyingTokenDecimals
  ) external view {
    cTokenAddress;
    chainlinkAggregatorAddress;
    chainlinkPriceBase;
    underlyingTokenDecimals;
    console.log("HfPriceOracleMock.setTokenConfigs");
  }

  function tokenConfig(address) external view returns (
    address chainlinkAggregatorAddress,
    uint256 chainlinkPriceBase,
    uint256 underlyingTokenDecimals
  ) {
    console.log("HfPriceOracleMock.tokenConfig");
    return (chainlinkAggregatorAddress, chainlinkPriceBase, underlyingTokenDecimals);
  }

  function transferOwnership(address newOwner) external pure {
    newOwner;
  }
}

// THIS FILE WAS AUTOGENERATED FROM THE FOLLOWING ABI JSON:
/*
[{"inputs":[{"internalType":"address","name":"ethUsdChainlinkAggregatorAddress_","type":"address"}],"stateMutability":"nonpayable","type":"constructor"},{"anonymous":false,"inputs":[{"indexed":true,"internalType":"address","name":"previousOwner","type":"address"},{"indexed":true,"internalType":"address","name":"newOwner","type":"address"}],"name":"OwnershipTransferred","type":"event"},{"anonymous":false,"inputs":[{"indexed":false,"internalType":"address","name":"cTokenAddress","type":"address"},{"indexed":false,"internalType":"address","name":"chainlinkAggregatorAddress","type":"address"},{"indexed":false,"internalType":"uint256","name":"chainlinkPriceBase","type":"uint256"},{"indexed":false,"internalType":"uint256","name":"underlyingTokenDecimals","type":"uint256"}],"name":"TokenConfigUpdated","type":"event"},{"inputs":[],"name":"ethUsdChainlinkAggregatorAddress","outputs":[{"internalType":"address","name":"","type":"address"}],"stateMutability":"view","type":"function"},{"inputs":[{"internalType":"contract CTokenInterface","name":"cToken","type":"address"}],"name":"getUnderlyingPrice","outputs":[{"internalType":"uint256","name":"","type":"uint256"}],"stateMutability":"view","type":"function"},{"inputs":[],"name":"isPriceOracle","outputs":[{"internalType":"bool","name":"","type":"bool"}],"stateMutability":"view","type":"function"},{"inputs":[],"name":"owner","outputs":[{"internalType":"address","name":"","type":"address"}],"stateMutability":"view","type":"function"},{"inputs":[],"name":"renounceOwnership","outputs":[],"stateMutability":"nonpayable","type":"function"},{"inputs":[{"internalType":"address","name":"addr","type":"address"}],"name":"setEthUsdChainlinkAggregatorAddress","outputs":[],"stateMutability":"nonpayable","type":"function"},{"inputs":[{"internalType":"address[]","name":"cTokenAddress","type":"address[]"},{"internalType":"address[]","name":"chainlinkAggregatorAddress","type":"address[]"},{"internalType":"uint256[]","name":"chainlinkPriceBase","type":"uint256[]"},{"internalType":"uint256[]","name":"underlyingTokenDecimals","type":"uint256[]"}],"name":"setTokenConfigs","outputs":[],"stateMutability":"nonpayable","type":"function"},{"inputs":[{"internalType":"address","name":"","type":"address"}],"name":"tokenConfig","outputs":[{"internalType":"address","name":"chainlinkAggregatorAddress","type":"address"},{"internalType":"uint256","name":"chainlinkPriceBase","type":"uint256"},{"internalType":"uint256","name":"underlyingTokenDecimals","type":"uint256"}],"stateMutability":"view","type":"function"},{"inputs":[{"internalType":"address","name":"newOwner","type":"address"}],"name":"transferOwnership","outputs":[],"stateMutability":"nonpayable","type":"function"}]
*/